image: docker.io/jonoh/docker-buildx-qemu

pipelines:
  default:
    - step:
        script:
          # - export DOCKER_HOST="tcp://${BITBUCKET_DOCKER_HOST_INTERNAL}:2375"
          - export DOCKER_DEFAULT_PLATFORM="linux/386,linux/amd64,linux/arm/v7,linux/arm64"
          - export DOCKER_HUB_REGISTRY="docker.io"
          - export DOCKER_HUB_IMAGE="${DOCKER_HUB_REGISTRY}/${DOCKER_HUB_NAMESPACE}/${BITBUCKET_REPO_SLUG}:${BITBUCKET_BRANCH}"
          - printenv | grep "^DOCKER_*" | sort
          - printenv | grep "^BITBUCKET_*" | sort
          - docker version
          - update-binfmts --enable
          - docker buildx create --name=docker-buildx-qemu --driver=docker-container --use
          - docker buildx inspect --bootstrap
          - echo "${DOCKER_HUB_TOKEN}" | docker login --username="${DOCKER_HUB_USER}" --password-stdin "${DOCKER_HUB_REGISTRY}"
          - docker buildx build --no-cache --pull --push --platform="${DOCKER_DEFAULT_PLATFORM}" --tag="${DOCKER_HUB_IMAGE}" .
